# Generated by Django 5.0.1 on 2024-01-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, upload_to='dishes/')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('catalogs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='catalog.catalog')),
            ],
            options={
                'verbose_name_plural': 'product',
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('order', 'catalogs'), name='unique_order_per_each_catalogs'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('id', 'slug')},
        ),
    ]
