# Generated by Django 5.0.1 on 2024-01-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_order_credit_card_number_remove_order_cvv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_processed',
            new_name='is_precessed',
        ),
    ]
