# Generated by Django 5.0.1 on 2024-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_footer_alter_catalogitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='is_manage',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
